import = [
	"~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
startup_mode = "Maximized"

# decorations = "Buttonless"

opacity = 0.5
blur = true

# option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 15
